### ISSUE TITLE
How to sample?

### ISSUE THREAD

**Issue by ShenZhang-Shin** [MCG-NJU/FlowDCN#1]
Hi, this is nice work to achieve arbitrary resolution generation. 
I can't wait to use this method to generate samples. However, I seem to have not found the sample command. 
Can you share your sample command?

**Comment by WANGSSSSSSS** [comment]
OK, i will add the train and inference command to README
![image](https://github.com/user-attachments/assets/1b671bca-b6fb-4c52-8602-6a4ec2044b6a)

**Comment by WANGSSSSSSS** [comment]
VAR Sampler source code is placed at:
https://github.com/MCG-NJU/FlowDCN/blob/main/src/diffusion/flow_matching/var_sampling.py#L23

**Comment by WANGSSSSSSS** [comment]
feel free to re-open if you encounter any problem
